# -*- coding: utf-8 -*-
"""biblio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X2NOtzivkqwPVIci-OLf0FD4o2YSN6Wh
"""

def cal_med(ap1,ap2,ap3):
  nf = ap1*0.4+ap2*0.4+ap3*0.2
  return nf

luiz = cal_med(7,8,9)
luiz